### ISSUE TITLE
დინამიური ელემენტები

### ISSUE THREAD

**Issue by tgagadze** [sebiskver/Social-Network#2]
დინამიურად რა ელემენტებიც უნდა გამიოსახოს ეგენი, გადასაყვანია დომის ფუნქციებად.

**Comment by ghost** [comment]
ხარაშო, ეხა ცოტა მოსაწესრიგებელია კოდი და მაგას მივხედავ მე.

**Comment by ghost** [comment]
ამაზე კაი რაღაც ვნახე გითჰაბს ჰგონია ტრელოსნაირი და იქ ვიმუშაოთ ამას დავხურავ.
